name: Workflow B

on: 
  pull_request_review:
    types:
      - submitted



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Workflow C was successful
        run: echo "${{ github.event.review.state }}"

      # Add your other steps for workflow-B
