name: Workflow B

on: 
  workflow_run:
    workflows: ["Workflow A", "Workflow D"]
    types:
      - completed
    branches:
      - master  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checking out repository

      - name: Running B
        run: echo "Workflow B running"  
      

