name: Workflow B

on: 
  pull_request_review:
    types:
      - submitted
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Workflow A was successful
        run: echo "${{ github.event.review.state }}"

      # Add your other steps for workflow-B
