name: Workflow B

on:
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if GitHub Actions Demo was successful
        run: echo "GitHub Actions Demo was successful!"

      # Add your other steps for workflow-B
