name: Workflow B

on: 
  workflow_run:
    workflows: 
      - Workflow A
    types:
      - completed
    branches:
      - master  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checking out repository

      - name: Print branch
        run: |-
          reflog_message=$(git reflog -1)
          merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")
          echo "You've just merged the branch \"$merged_branch_name\"

