name: Workflow B

on: 
  workflow_run:
    workflows: 
      - Workflow A
    types:
      - completed
    branches:
      - master  


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checking out repository
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
