name: Workflow C

on:
  workflow_run:
    workflows: ["Workflow B"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Workflow B was successful
        run: echo "Workflow B was successful!"

      # Add your other steps for workflow-B
